Atmosphere-NX/Atmosphere

exosphere/README.md

Exosphere isn't a french word, we need to fix that!

Improve french for Exosphère

---

exosphere/start.cold.s
exosphere/start.warm.s

The second operand needs to be an immediate

start.cold/warm: Correct MSR instructions

---

exosphere/gcm.c
exosphere/package2.c
exosphere/randomcache.c
exosphere/smc_user.c
exosphere/titlekey.c
exosphere/userpage.c

Just some inclusions that were missing

Add missing string.h includes

---

exosphere/memory_map.h

The only lingering issue is that there's too few arguments to some calls to mmu_map_block_range (missing level before the tbl argument), which I don't know what was intended to be passed in those cases.

memory_map: Fix most compilation issues

---

stratosphere/boot/source/boot_main.cpp

Changes from switchbrew/libnx@2818c99dea1d4e8079469e6a6d13c8b436549d4b

boot: Use fsdevMountSdmc & fsdevUnmountAll

---

fusee/fusee-secondary/src/nxboot.c

Using NAND doens't really make sense

Replace NAND by eMMC

---

stratosphere/creport/source/creport_code_info.hpp
stratosphere/creport/source/creport_crash_report.hpp
stratosphere/creport/source/creport_thread_info.hpp
stratosphere/fs_mitm/source/fs_istorage.hpp
stratosphere/fs_mitm/source/fsmitm_layeredrom.cpp
stratosphere/fs_mitm/source/fsmitm_romfsbuild.hpp
stratosphere/fs_mitm/source/fsmitm_service.hpp
stratosphere/fs_mitm/source/fsmitm_worker.cpp
stratosphere/fs_mitm/source/mitm_query_service.cpp
stratosphere/libstratosphere/include/stratosphere/domainowner.hpp
stratosphere/libstratosphere/include/stratosphere/hossynch.hpp
stratosphere/libstratosphere/source/multithreadedwaitablemanager.cpp
stratosphere/libstratosphere/source/waitablemanager.cpp
stratosphere/loader/source/ldr_map.hpp
stratosphere/loader/source/ldr_ro_service.hpp
stratosphere/pm/source/pm_debug_monitor.cpp
stratosphere/pm/source/pm_info.cpp
stratosphere/pm/source/pm_process_wait.hpp
stratosphere/pm/source/pm_registration.cpp
stratosphere/pm/source/pm_registration.hpp
stratosphere/pm/source/pm_shell.cpp
stratosphere/sm/source/sm_user_service.hpp

A set of minor cleanup commits.
Each commit is self contained and can be reviewed independently.

stratosphere: Minor cleanup

---

stratosphere/pm/source/pm_debug_monitor.cpp
stratosphere/pm/source/pm_debug_monitor.hpp
stratosphere/pm/source/pm_resource_limits.cpp
stratosphere/pm/source/pm_resource_limits.hpp

pm: add AtmosphereGetCurrentLimitInfo command to pm:dmnt

---

docs/building.md
docs/components/exosphere.md
docs/components/fusee/BCT.md
docs/components/fusee/fusee.md
docs/components/stratosphere.md
docs/components/thermosphere.md
docs/components/troposphere.md
docs/main.md
docs/modules/boot.md
docs/modules/creport.md
docs/modules/fs_mitm.md
docs/modules/loader.md
docs/modules/pm.md
docs/modules/sm.md
docs/roadmap.md

I worked with Hylian on Discord to create Documentation for Atmosphère. We created documentation on all the components of Atmosphère as well as the sysmodules. We also included a building guide and release roadmap.

Add Documentation

---

docs/changelog.md

Added info on Atmosphere 0.7.3 to the changelog.

Update Changelog for 0.7.3

---

docs/changelog.md

Updated the version changelog with info on Atmosphère 0.7.4.

Update Changelog for 0.7.4

---

stratosphere/loader/source/ldr_content_management.cpp

This allows overriding any app with HBL by using `hbl_tid=app` in `loader.ini`. Useful with `override_key=R`, to run HBL on top of any game just by pressing R when launching it.

loader: add 'override any app' feature

---

fusee/fusee-secondary/src/kernel_patches.c

Add offset based patching
Add svcControlCodeMemory patches for ver. 5, 6, 7
Reviewer:
@SciresM

[Fusee] Refactor Kernel patching

---

README.md

Should be reswitched.team, 
the other one (reswitched.tech) is not available

Update readme.md reswitched website

---

stratosphere/ams_mitm/source/fs_mitm/fsmitm_romfsbuild.cpp
stratosphere/ams_mitm/source/fs_mitm/fsmitm_romfsbuild.hpp
stratosphere/ams_mitm/source/set_mitm/setsys_settings_items.cpp

Using delete instead of delete[] on a pointer given by new[] is
undefined behaviour.

fs_mitm: Fix mismatched new[] / delete

---

docs/cheats.md

This covers changes made to Opcode 10 as well as the new 0xC0 opcode

Update cheat docs with latest opcodes

---

docs/components/fusee/BCT.md

It was severely outdated and lacked all mentions of new features.

Update BCT.md to bring it into the modern age.

---

docs/building.md

- individually listed packages required when using (dkp-)packman.
- added sept dependencies
- added requirement to use -r flag
- added recommendation for zip (for use if someone wants to make dist)

Add additional dependency information

---

stratosphere/ams_mitm/source/fs_mitm/fsmitm_service.cpp

something that allows you to decide which title to redirect games saves to sd and which does not

simple sd_save flag

---

libraries/libstratosphere/include/stratosphere.hpp
libraries/libstratosphere/include/stratosphere/lmem.hpp
libraries/libstratosphere/include/stratosphere/lmem/impl/lmem_impl_common.hpp
libraries/libstratosphere/include/stratosphere/lmem/lmem_common.hpp
libraries/libstratosphere/include/stratosphere/lmem/lmem_exp_heap.hpp
libraries/libstratosphere/include/stratosphere/lmem/lmem_unit_heap.hpp
libraries/libstratosphere/source/lmem/impl/lmem_impl_common_heap.cpp
libraries/libstratosphere/source/lmem/impl/lmem_impl_common_heap.hpp
libraries/libstratosphere/source/lmem/impl/lmem_impl_exp_heap.cpp
libraries/libstratosphere/source/lmem/impl/lmem_impl_exp_heap.hpp
libraries/libstratosphere/source/lmem/impl/lmem_impl_unit_heap.cpp
libraries/libstratosphere/source/lmem/impl/lmem_impl_unit_heap.hpp
libraries/libstratosphere/source/lmem/lmem_common.cpp
libraries/libstratosphere/source/lmem/lmem_exp_heap.cpp
libraries/libstratosphere/source/lmem/lmem_unit_heap.cpp

This doesn't implement lmem::FrameHeap, but almost nothing uses that anyway.

lmem: Implement UnitHeap, ExpHeap

---

libraries/libstratosphere/include/stratosphere/fs/fsa/fs_ifile.hpp
libraries/libstratosphere/include/stratosphere/fssystem.hpp
libraries/libstratosphere/include/stratosphere/fssystem/fssystem_partition_file_system.hpp
libraries/libstratosphere/include/stratosphere/fssystem/fssystem_partition_file_system_meta.hpp
libraries/libstratosphere/source/fssystem/fssystem_partition_file_system.cpp
libraries/libstratosphere/source/fssystem/fssystem_partition_file_system_meta.cpp
libraries/libvapours/include/vapours.hpp
libraries/libvapours/include/vapours/allocator.hpp
libraries/libvapours/include/vapours/results/fs_results.hpp

As per title. Used for opening PFS0s as filesystems.

Implement PartitionFileSystemCore

---

libraries/libstratosphere/include/stratosphere.hpp
libraries/libstratosphere/include/stratosphere/nim.hpp
libraries/libstratosphere/include/stratosphere/nim/nim_network_install_manager_api.hpp
libraries/libstratosphere/include/stratosphere/nim/nim_system_update_task_id.hpp
libraries/libstratosphere/include/stratosphere/nim/nim_task_id_common.hpp
libraries/libstratosphere/source/nim/nim_network_install_manager_api.cpp

To be merged after https://github.com/switchbrew/libnx/pull/390 is merged.

nim: add DestroySystemUpdateTask/ListSystemUpdateTask

---

libraries/libstratosphere/include/stratosphere/ncm.hpp
libraries/libstratosphere/include/stratosphere/ncm/ncm_content_manager_impl.hpp
libraries/libstratosphere/include/stratosphere/ncm/ncm_i_content_manager.hpp
libraries/libstratosphere/include/stratosphere/ncm/ncm_i_content_meta_database.hpp
libraries/libstratosphere/include/stratosphere/ncm/ncm_memory_report.hpp
libraries/libstratosphere/source/ncm/ncm_content_manager_impl.cpp
libraries/libstratosphere/source/ncm/ncm_content_meta_database_impl.cpp
libraries/libstratosphere/source/ncm/ncm_content_meta_database_impl.hpp
libraries/libstratosphere/source/ncm/ncm_memory_report.cpp
libraries/libstratosphere/source/ncm/ncm_remote_content_manager_impl.hpp
libraries/libstratosphere/source/ncm/ncm_remote_content_meta_database_impl.hpp
stratosphere/ncm/source/ncm_main.cpp

ncm: update to 10.0.0

---

docs/building.md

add dependency needed since 90d754f920e099d581d250145eeb00e83303dac0

Add switch-jpeg-turbo to the list of dependencies.

---

stratosphere/dmnt/source/cheat/dmnt_cheat_service.cpp
stratosphere/dmnt/source/cheat/dmnt_cheat_service.hpp
stratosphere/dmnt/source/cheat/impl/dmnt_cheat_api.cpp
stratosphere/dmnt/source/cheat/impl/dmnt_cheat_api.hpp
stratosphere/dmnt/source/cheat/impl/dmnt_cheat_vm.cpp
stratosphere/dmnt/source/cheat/impl/dmnt_cheat_vm.hpp

This addresses both the request in #874 as well as a request @WerWolv brought to me in private.
It will be merged following confirmation by the involved parties.

Dmnt: Add break/continue commands, add static register api.

---

libraries/libstratosphere/include/stratosphere/ncm.hpp
libraries/libstratosphere/include/stratosphere/ncm/ncm_install_task_base.hpp
libraries/libstratosphere/include/stratosphere/ncm/ncm_package_system_downgrade_task.hpp
libraries/libstratosphere/include/stratosphere/ncm/ncm_package_system_update_task.hpp
libraries/libstratosphere/source/ncm/ncm_package_system_downgrade_task.cpp

Implements the foundations necessary for firmware downgrading.

ncm: implement firmware downgrading

---

troposphere/daybreak/source/ui.cpp

daybreak: sort folders alphabetically and only display success message on success

---

libraries/libstratosphere/include/stratosphere/ncm/ncm_content_storage.hpp

ncm: Mark two variables as const

ncm: Mark two variables as const

---

troposphere/daybreak/source/main.cpp
troposphere/daybreak/source/ui.cpp
troposphere/daybreak/source/ui.hpp
troposphere/daybreak/source/ui_util.cpp
troposphere/daybreak/source/ui_util.hpp

- Improved text area text spacing
- Improved clarity of driver variant buttons
- Changed selection highlight colour to purple
- Automatically detect current driver variant and select button based on that
- Check ams api version
- Warn for RCM patched units

daybreak: various ux improvements

---

troposphere/daybreak/source/ui.cpp

daybreak: address nitpicks

---

troposphere/daybreak/source/main.cpp
troposphere/daybreak/source/ui.cpp
troposphere/daybreak/source/ui.hpp

daybreak: Added support for factory resetting

---

libraries/config/arch/arm64/arch.mk
libraries/config/arch/arm64/cpu/cortex_a57/cpu.mk
libraries/libmesosphere/include/mesosphere/board/generic/kern_k_device_page_table.hpp
libraries/libmesosphere/include/mesosphere/kern_common.hpp
libraries/libmesosphere/include/mesosphere/kern_select_device_page_table.hpp
libraries/libmesosphere/source/kern_k_memory_layout.board.nintendo_nx.cpp
libraries/libmesosphere/source/kern_k_memory_layout.cpp
libraries/libvapours/include/vapours/svc/board/generic/svc_device_name.hpp
mesosphere/kernel/source/arch/arm64/init/kern_init_core.cpp
mesosphere/kernel/source/arch/arm64/init/start.s
mesosphere/kernel_ldr/source/arch/arm64/start.s
mesosphere/kernel_ldr/source/kern_init_loader.cpp

This makes porting the kernel to other boards easier.

Kernel: Improve genericity of code.

---

troposphere/daybreak/source/ui.cpp

daybreak: update for hid refactor

---

troposphere/daybreak/nanovg/.gitrepo
troposphere/daybreak/nanovg/include/nanovg/framework/CApplication.h
troposphere/daybreak/nanovg/source/framework/CApplication.cpp

Updated daybreak's nanovg for the latest libnx

git subrepo pull troposphere/daybreak/nanovg/

---

docs/components/modules/ams_mitm.md

Move set_mitm H3's under correct H2 element

Correct ams_mitm.md formatting

---

libraries/libstratosphere/include/stratosphere/ams/impl/ams_system_thread_definitions.hpp
libraries/libstratosphere/include/stratosphere/fs.hpp
libraries/libstratosphere/include/stratosphere/fs/fs_i_event_notifier.hpp
libraries/libstratosphere/include/stratosphere/fssrv.hpp
libraries/libstratosphere/include/stratosphere/fssrv/sf/fssrv_sf_i_event_notifier.hpp
libraries/libstratosphere/include/stratosphere/htclow/impl/htclow_internal_types.hpp
libraries/libstratosphere/include/stratosphere/ncm/ncm_system_content_meta_id.hpp
libraries/libstratosphere/source/fs/fs_sd_card.cpp
libraries/libstratosphere/source/fs/fsa/fs_user_filesystem_for_debug.cpp
libraries/libstratosphere/source/fs/impl/fs_event_notifier_object_adapter.hpp
libraries/libstratosphere/source/htclow/ctrl/htclow_service_channel_parser.cpp
stratosphere/TioServer/Makefile
stratosphere/TioServer/TioServer.json
stratosphere/TioServer/source/tio_file_server.cpp
stratosphere/TioServer/source/tio_file_server.hpp
stratosphere/TioServer/source/tio_file_server_htcs_server.cpp
stratosphere/TioServer/source/tio_file_server_htcs_server.hpp
stratosphere/TioServer/source/tio_file_server_packet.hpp
stratosphere/TioServer/source/tio_file_server_processor.cpp
stratosphere/TioServer/source/tio_file_server_processor.hpp
stratosphere/TioServer/source/tio_main.cpp
stratosphere/TioServer/source/tio_sd_card_observer.cpp
stratosphere/TioServer/source/tio_sd_card_observer.hpp

This PR is not done, but tma2 is being merged into master periodically to prevent undesirable divergence of the development and master branches. The previous tma2 PR grew to be ~40000 lines of code, which is far too many to have pending integration.
The following are some checklists for tma2.
Note that not everything will make it into this PR in particular.
List of stuff to do for TioServer sysmodule:
List of stuff to do for Starlink:
List of stuff to do for `cs` sysmodule, likely a separate PR:
List of stuff to do for `dmnt.gen2` sysmodule, likely a separate PR:
Completed in previous PRs:
List of stuff to do for `htc` sysmodule (mostly done):

[tma2] [Ongoing] Continue implementing modules for tma2.

---

troposphere/daybreak/source/ui.cpp

daybreak: Added a warning when resetting to factory settings

---

libraries/libstratosphere/source/ncm/ncm_content_storage_impl.cpp
libraries/libstratosphere/source/ncm/ncm_content_storage_impl.hpp

Despite the lack of additions of new commands, 11.0.0 did in fact have a change to NCM to ListContentId. It should now once again be accurate.

ncm: Updated ListContentId for 11.0.0

---

.github/ISSUE_TEMPLATE/bug_report.md

Update issue template to reflect what type of system the user is using.

Issue template reflects EmuMMC vs SysNAND

---

troposphere/daybreak/source/main.cpp
troposphere/daybreak/source/ui.cpp
troposphere/daybreak/source/ui.hpp

https://github.com/Atmosphere-NX/Atmosphere/pull/1586 but with the requested changes

Add arguments support to Daybreak

---

exosphere/program/source/smc/secmon_smc_info.cpp
exosphere/program/source/smc/secmon_smc_info.hpp
libraries/libexosphere/include/exosphere/fuse.hpp
libraries/libexosphere/source/fuse/fuse_api.cpp
libraries/libstratosphere/include/stratosphere/ams/impl/ams_system_thread_definitions.hpp
libraries/libstratosphere/include/stratosphere/ncm/ncm_system_content_meta_id.hpp
libraries/libstratosphere/include/stratosphere/settings/settings_types.hpp
libraries/libstratosphere/include/stratosphere/spl/spl_api.hpp
libraries/libstratosphere/include/stratosphere/spl/spl_types.hpp
libraries/libstratosphere/source/settings/impl/settings_key_value_store.cpp
libraries/libstratosphere/source/settings/impl/settings_key_value_store.hpp
libraries/libstratosphere/source/settings/impl/settings_spl.cpp
libraries/libstratosphere/source/settings/impl/settings_spl.hpp
libraries/libstratosphere/source/settings/impl/settings_static_object.hpp
libraries/libstratosphere/source/settings/impl/settings_system_data.cpp
libraries/libstratosphere/source/settings/impl/settings_system_data.hpp
libraries/libstratosphere/source/settings/impl/settings_system_save_data.cpp
libraries/libstratosphere/source/settings/impl/settings_system_save_data.hpp
libraries/libvapours/include/vapours/results/settings_results.hpp
stratosphere/ams_mitm/source/set_mitm/setsys_mitm_service.cpp
stratosphere/ams_mitm/source/set_mitm/setsys_mitm_service.hpp
stratosphere/ams_mitm/source/set_mitm/settings_sd_kvs.cpp

This forms the foundation for save data reading/writing required for a complete settings reimplementation.

settings: implement KeyValueStore

---

libraries/libmesosphere/source/arch/arm64/kern_k_thread_context.cpp

KThreadContext: Use El0PsrMask constant in GetUserContext
