exosphere/userpage.h
Mismatch between header and source file.
=> userpage: fix declarations

exosphere/mmu.h
=> mmu: fix typo

exosphere/se.c
`i >= 0` will never be false. (`i` is unsigned.)
=> se: fix infinite loop in shift_left_xor_rb

exosphere/package2.c
Identifiers can't begin with a number
=> package2: Correct variable name for new device key source

exosphere/cpu_context.c
Breaks out the one header not related to string.h from #17
=> cpu_context: Add missing include

exosphere/gcm.c
It's not well-formed to subscript a pointer to void
=> gcm: Convert source data to a uint8_t pointer before subscripting it in gcm_decrypt_key

exosphere/package2.c
This is more concise and also compiles (the previous code was missing an & on the source argument)
=> package2: Use assignment instead of memcpy in decrypt_and_validate_header

exosphere/package2.c
header is a local on the stack, so this should just be regular member accessing
With this, all errors for the most part should be resolved in package2.c
=> package2: Correct -> to . in load_package2

exosphere/randomcache.c
Failure to update `g_random_cache_high` in `g_random_cache_low > high_plus_one` branch.
=> randomcache: Typo in randomcache_refill

exosphere/start.cold.s, exosphere/start.warm.s
DSB requires specifying the barrier option
=> start.cold/warm.s: Correct DSB instruction instances

exosphere/mmu.h
mmu_unmap_range was also passing the physical address.
If this is actually unnecessary and the argument itself should be removed instead, then I can just modify this change to do that instead.
=> mmu: Fix compilation issues

exosphere/mmu.h
It's unused. I had intended to remove it in #27 but I must have forgotten to commit it.
=> mmu: Remove phys_addr parameter from mmu_unmap_range

exosphere/cpu_context.c, exosphere/timers.c
Also resolves implicit definition warnings for wait by including the necessary header where applicable
With this, it builds all the way to the assembly portion of compilation
=> timers: Fix identifier name in wait's spin-lock

exosphere/se.c
Resolves implicit declaration warnings for memcpy and memset. Must have missed this one in #17
=> se: Add missing string.h include

exosphere/smc_user.c
Resolves an implicit declaration warning for gcm_decrypt_key
=> smc_user: Add missing gcm.h include

exosphere/src/se.c
We can just initialize the array to be zeroed out. This is safer and less error-prone,
since the initializer is now associated with the variable directly, making it
impossible to put code relying on the zeroed out state before it (unlike with memset).
=> se: Remove memset in se_perform_aes_block_operation

exosphere/src/mc.c
I'm assuming the switch was intended to be removed, but was accidentally left in.
=> mc: Remove dead code in get_carveout_by_id

exosphere/src/fuse.c
A separate variable isn't particularly necessary here, and given that the type
is unsigned, we only need to test the upper bound.
This also resolves two -Wtype-limits warnings
=> fuse: simplify checks in fuse_get_reserved_odm and fuse_get_spare_bit

exosphere/src/lock.h, exosphere/src/smc_api.c
Provides the same assembly output while also using the standardized interface
e.g. The identical output for both cases:
```
0000000000000000 <set_priv_smc_in_progress>:
0:   90000000    adrp    x0, 0 <set_priv_smc_in_progress>
4:   91000000    add x0, x0, #0x0
8:   52800022    mov w2, #0x1                    // #1
c:   d503201f    nop
10:   085ffc01    ldaxrb  w1, [x0]
14:   08037c02    stxrb   w3, w2, [x0]
18:   35ffffc3    cbnz    w3, 10 <set_priv_smc_in_progress+0x10>
1c:   72001c3f    tst w1, #0xff
20:   54ffff81    b.ne    10 <set_priv_smc_in_progress+0x10>  // b.any
24:   d65f03c0    ret
```
=> lock: Use stdatomic.h

exosphere/src/memory_map.h
Since the return value isn't a pointer thing doesn't have much use.
=> memory_map: Remove unnecessary const

fusee/fusee-secondary/src/key_derivation.c, fusee/fusee-secondary/src/key_derivation.h
=> BisPartition_t was missing SAFE, meaning User and System were using wrong key_source

stratosphere/libstratosphere/include/stratosphere/ipc_templating.hpp
`f(x, x++)` is unspecified behaviour in C++. An implementation could
evaluate arguments from left to right or from right to left.
`T(r.Buffers[a_index], r.BufferSizes[a_index++])` might
access the wrong buffer if `a_index++` is evaluated before the first
argument.
Fixes -Wsequence-point warnings
=> ipc_templating: Avoid depending on order of evaluation

stratosphere/boot/source/boot_main.cpp
* Fix invalid usage of svcQueryIoMapping. As far as I understand, it's used to get a pointer so passing `nullptr` to it for the returned pointer parameter does not make sense.
* Fix build issues because of gpio_base_vaddr not being passed
* Make the helper functions internally linked (not a fix but a tiny cleanup)
=> boot: Fix usage of svcQueryIoMapping and building

stratosphere/loader/source/ldr_debug_monitor.cpp, stratosphere/loader/source/ldr_shell.cpp
%z should be used for size_t, otherwise the wrong value may be printed.
Fixes two -Wformat warnings.
=> ldr: Fix printf format string for size_t

fusee/fusee-primary/src/init.c, fusee/fusee-primary/src/stage2.h, fusee/fusee-secondary/src/init.c
fixes a couple bugs introduced by e8306361f06132fc1ecc14070bd77c2b4e564dcd
~stage2 is only receiving the first 18 bytes of the bct, don't know what's going on there yet~
=> Fix stage2_args_t mismatch

stratosphere/libstratosphere/include/stratosphere/iserviceobject.hpp, stratosphere/libstratosphere/include/stratosphere/servicesession.hpp, stratosphere/libstratosphere/include/stratosphere/systemevent.hpp, stratosphere/loader/source/ldr_debug_monitor.hpp, stratosphere/loader/source/ldr_process_manager.hpp, stratosphere/loader/source/ldr_ro_service.hpp, stratosphere/loader/source/ldr_shell.hpp, stratosphere/pm/source/pm_boot_mode.hpp, stratosphere/pm/source/pm_debug_monitor.hpp, stratosphere/pm/source/pm_info.hpp, stratosphere/pm/source/pm_process_wait.hpp, stratosphere/pm/source/pm_shell.hpp, stratosphere/sm/source/sm_manager_service.hpp, stratosphere/sm/source/sm_user_service.hpp
These keywords were introduced in C++11 for the sake of catching bugs and improving code expressiveness:
* "override" ensures the given member function actually overrides one of the base class's member functions (which can be easy to mess up by picking the wrong types or function names)
* "final" classes may not be inherited from; this implies that none of its child methods will ever be overridden. This is useful when browsing through the source (easy to identify concrete classes that will be instantiated), and it also helps the compiler optimizer at devirtualization.
=> Use "final" and "override" where appropriate

fusee/fusee-primary/src/sdmmc.c, fusee/fusee-secondary/src/sdmmc.c
According to Tegra X1 Series Processors Silicon Errata there is possible
misalignment of received data which results in a CRC error. The issue is
present only in SDR50 mode.
I didn't check this code. I wanted to start discussion about this on the discord, however I don't have permissions to post to the development channel. Hence I decided a pull request is going to be best way to get it mentioned/discussed.
I didn't yet traverse through the full datasheet nor the driver code, so the change might break something.
=> Set SDMMC controller to SDR104 as a workaround

exosphere/src/uart.c, exosphere/src/uart.h
Add UART register enumerators for better access to the following registers
- VENDOR_STATUS_0_0
- LSR_0
- LCR_0
- IIR_FCR_0
Editing uart_wait_idle() to take `UartVendorStatus` as a parameter
=> Add UART register enumerators

fusee/fusee-secondary/Makefile, fusee/fusee-secondary/src/package2.c, fusee/fusee-secondary/src/stratosphere.c
Two things in this PR:
1) The offset for reading kip1s was never incremented so the merging function would only ever try to merge the first KIP1 of each INI1. Sample hactool output for a package2 built with this fix: https://pastebin.com/WDVAwdMe
2) Based on the suggestion by Thog, the second commit fixes package2 verification by passing along the data to be hashed. For this one I'm not sure if this is good style so feel free to let me know and I can change or remove it from the PR :)
Oh, and a small Makefile fix.
=> package2 verification and ini1 merging fixes

README.md
Loosely based on https://github.com/Atmosphere-NX/Atmosphere/projects - such an overview was really needed, and now the information is in the place where people will actually find it :)
=> Add component overview to the readme

stratosphere/pm/source/pm_debug_monitor.cpp, stratosphere/pm/source/pm_debug_monitor.hpp
Adds a command to `pm:dmnt` to obtain a process handle from PID. Tested working on 3.0.0.
=> PM: add GetProcessHandle command to pm:dmnt

stratosphere/sm/Makefile, stratosphere/sm/source/sm_registration.cpp
This lets us do things like accessing `fsp-ldr` without having to kill `ldr`. The default I chose is 8.
Tested working on 3.0.0.
=> SM: Add compile-time option to put a lower bound on session limits

fusee/fusee-primary/src/sdmmc.c, fusee/fusee-secondary/src/sdmmc.c
Properly configure pull up and pull down offsets for autocal.
Run autocal prior to every transfer.
Prevent race conditions in sdmmc_wait_for_event() - make sure the fault
handler has highest priority, then the target irq, state conditions and
finally the error mask.
Do not clear all bits (|=) when acknowledging fault conditions,
only acknowledge the fault conditions itself.
Enable interrupts before preparing command registers - if sdmmc is fast
enough it can actually finish transfer before we enabled the interrupts.
Enabling interrupts clears the COMMAND COMPLETE status bit.
Temporarily print all the sdmmc messages in stage2 - for yet unknown
reason respecting the log level results in some failures.
This results in working microsd card in stage2 on my switch with Samsung
EVO+ 256GB …
=> Fix race conditions and misconfiguration in sdmmc

fusee/fusee-primary/src/sdmmc.c, fusee/fusee-secondary/src/sdmmc.c
As per TRM, periodic autocalibration should only be run on the uSD controllers. Given only SDMMC1 is relevant on the switch, limit it to this controller.
=> fusee: Run periodic autocal only on the uSD controller

fusee/fusee-primary/src/car.h, fusee/fusee-primary/src/sdmmc.c, fusee/fusee-primary/src/sdmmc.h, fusee/fusee-secondary/src/car.h, fusee/fusee-secondary/src/sdmmc.c, fusee/fusee-secondary/src/sdmmc.h
Use 204 MHz as host clock in SDR104 mode instead of 136 MHz.
Due to this, also change the frequency init divider so the
initialization frequency is below 400 kHz.
This makes the clocks for SDMMC1 in all modes to match the TRM table.
Make it clear in the code that HS200/HS400 modes in fact use PLLP_OUT0
and not PLLC4_OUT2_LJ like the comment suggest. In fact selecting the
PLLC4_OUT2_LJ as clock source results in freeze after switching to
HS200/HS400 mode. This is most likely related to the PLLC4 not being
enabled, but it should be checked later.
Set the HS200/HS400 divider to 3, as this is what the code really did
set prior to this change - so this commit does not change that.
Configure Legacy 12 MHz clock to run at 12 MHz using the SW default
configuration (as per TRM) for the SDMMC …
=> Rework sdmmc clocking configuration

fusee/fusee-secondary/src/kernel_patches.c
Ran into two issues in the kernel_patches.c file for fusee_secondary, this fixes them.
- Macro wasn't using the "vers" variable, was instead adding the text "vers_"
- "search_pattern" was always failing, comparing it to the one in Luma3DS, the comparison was different. This resolved it.
=> Fix a few issues in the secondary kernel_patches.c file

stratosphere/fs_mitm/source/fs_istorage.hpp, stratosphere/fs_mitm/source/fsmitm_layeredrom.cpp, stratosphere/fs_mitm/source/fsmitm_layeredrom.hpp, stratosphere/fs_mitm/source/fsmitm_main.cpp, stratosphere/fs_mitm/source/fsmitm_romfsbuild.cpp, stratosphere/fs_mitm/source/fsmitm_romfsbuild.hpp, stratosphere/fs_mitm/source/fsmitm_service.cpp, stratosphere/fs_mitm/source/fsmitm_service.hpp, stratosphere/fs_mitm/source/fsmitm_worker.cpp, stratosphere/fs_mitm/source/imitmserviceobject.hpp, stratosphere/fs_mitm/source/mitm_session.hpp, stratosphere/libstratosphere/include/meta_tools.hpp, stratosphere/libstratosphere/include/stratosphere/domainowner.hpp, stratosphere/libstratosphere/include/stratosphere/ievent.hpp, stratosphere/libstratosphere/include/stratosphere/ipcsession.hpp, stratosphere/libstratosphere/include/stratosphere/iserver.hpp, stratosphere/libstratosphere/include/stratosphere/isession.hpp, stratosphere/libstratosphere/include/stratosphere/waitablemanager.hpp, stratosphere/libstratosphere/include/stratosphere/waitablemanagerbase.hpp, stratosphere/libstratosphere/source/multithreadedwaitablemanager.cpp, stratosphere/libstratosphere/source/waitablemanager.cpp, stratosphere/loader/source/ldr_launch_queue.cpp, stratosphere/loader/source/ldr_main.cpp, stratosphere/loader/source/ldr_nro.cpp, stratosphere/loader/source/ldr_registration.cpp, stratosphere/loader/source/ldr_registration.hpp, stratosphere/pm/source/pm_registration.cpp, stratosphere/sm/source/sm_registration.cpp
Only touched a couple of instances for each of the following, but it's a start and it might be some inspiration on how new code could be written:
* Prefer algorithms over raw loops
* Prefer RAII (`unique_ptr`/`vector`) over raw pointers
* Prefer `enum class` over a C-style `enum` in cases where the enum values where prefixed with the enum type name anyway
* Prefer `std::variant` over explicitly tagged unions
* Prefer `default` constructors/destructors over empty ones
* Prefer `emplace_back` over `push_back` for initialization `vector` elements inplace rather than by copy
* Prefer direct member initialization over initialization in the constructor
* Prefer `std::array` over C-style arrays
Other than modernizing the codebase, this actually fixes at least some bugs where `delete` was used …
=> Modernize C++ usage

stratosphere/pm/source/pm_registration.cpp, stratosphere/pm/source/pm_registration.hpp, stratosphere/pm/source/pm_shell.cpp
This replaces the magic numbers used to interact with `Registration::Process.flags` with a set of enum constants. I would appreciate feedback on the names of these constants, as well as feedback on what to do about the notes I made when trying to figure out the meaning of each flag and event type. Should I keep the notes the way they are, remove them, or try to clean them up?
~~I would also appreciate if someone could verify that I didn't break any of the logic accidentally (probably by either accidentally replacing a flag with another one, or by changing the logic for flags 0x10 and 0x20), since I can't test on hardware at the moment.~~ Tested working on 3.0.0.
=> PM: Remove magic numbers for flags and events to improve readability and understandability

fusee/fusee-primary/src/utils.c, fusee/fusee-secondary/src/utils.c
fusee-primary and secondary were linking to sys/wait.h, which didn't quite work :slightly_smiling_face: 
Unrelated: I'm noticing (on my 4.0.1 system) exosphere's bootup_misc_mmio is freezing the fusee-secondary. I can add a panic before `sync_with_nx_bootloader(NX_BOOTLOADER_STATE_FINISHED_4X);` to verify that exosphere continues execution, but fusee-secondary freezes before it can get `SECMON_AWAKE`. Not sure how I can help debug further, or if this is already known.
=> Define wait() in fusee-primary/secondary

fusee/fusee-secondary/src/fs_dev.c
Previously this was casting the same unassigned variable that was being assigned to.
=> fusee-secondary/fs_dev: Correct uninitialized cast within fsdev_seek()

fusee/fusee-secondary/src/chainloader.c
Previously both the if and else conditions were the same.
Probably needs an extra set of eyes on this, just to ensure the right branch is being changed here.
=> fusee-secondary: Correct else-if condition in xmemmove()

fusee/fusee-primary/src/chainloader.c
This was corrected in 4b8455baf91d8699a663341c135c91c34f0a7816 for fusee-secondary, but I neglected to also fix it in fusee-primary (my bad!)
=> fusee-primary: Fix always false conditional in xmemmove

docs/changelog.md, docs/main.md, docs/modules/loader.md, docs/roadmap.md
I have updated various sections of the documentation to reflect Atmosphère 0.7.2.
A couple of key changes I would like to mention:
The release roadmap is now a list of upcoming features. I have done this because as far as I am aware, we do not yet know in what version certain features will be added. When a feature on this list is added, I will remove it from the list.
I have added a changelog to the documentation. This log contains release notes for all versions of Atmosphère.
Finally, I have updated the HBL section of loader.md to explain how we are able to use any game on the Home Menu to launch hbmenu, as opposed to launching it from the album.
=> Update Documentation for 0.7.2

stratosphere/loader/source/ldr_content_management.cpp, stratosphere/loader/source/ldr_content_management.hpp, stratosphere/loader/source/ldr_npdm.cpp, stratosphere/loader/source/ldr_npdm.hpp, stratosphere/loader/source/ldr_nso.cpp, stratosphere/loader/source/ldr_nso.hpp, stratosphere/loader/source/ldr_process_creation.cpp, stratosphere/loader/source/ldr_shell.cpp, stratosphere/loader/source/ldr_shell.hpp
Currently WIP, as I've not yet finished writing anything to test this. Posting here for review.
One thing that I'm noticing is that the content management code is becoming very convoluted. Perhaps there should be a different design where there is a stack of content providers that are queried for a given TID+NSO index, where each content provider can either supply the file, reject the file, or pass the request along to the next content provider.
- ExternalContentSource provider overrides everything
- HBL content provider
- SD content provider
- ExeFS content provider
This type of design would also allow a more powerful extension so that rather than using `SetExternalContentSource` to override a specific title's contents, a sysmodule could use a more powerful `AddExternalContentProvider` …
=> loader: add SetExternalContentSource extension

Makefile, stratosphere/fs_mitm/source/fs_istorage.hpp, stratosphere/fs_mitm/source/fs_shim.c, stratosphere/fs_mitm/source/fs_shim.h, stratosphere/fs_mitm/source/fsmitm_boot0storage.cpp, stratosphere/fs_mitm/source/fsmitm_boot0storage.hpp, stratosphere/fs_mitm/source/fsmitm_main.cpp, stratosphere/fs_mitm/source/fsmitm_romstorage.hpp, stratosphere/fs_mitm/source/fsmitm_service.cpp, stratosphere/fs_mitm/source/fsmitm_service.hpp, stratosphere/fs_mitm/source/fsmitm_utils.cpp, stratosphere/fs_mitm/source/fsmitm_utils.hpp, stratosphere/fs_mitm/source/sha256.c, stratosphere/fs_mitm/source/sha256.h, stratosphere/fs_mitm/source/sha256_armv8.s, stratosphere/pm/source/pm_boot2.cpp, stratosphere/set_mitm/source/setsys_mitm_service.hpp, stratosphere/sm/Makefile, stratosphere/sm/source/sm_registration.cpp, stratosphere/sm/source/sm_registration.hpp, stratosphere/sm/source/sm_user_service.cpp, stratosphere/sm/source/sm_user_service.hpp
This adds some basic protections to NAND rw.
Notably:
-Nobody can write to CAL0 any more, and a backup (not readable by homebrew) is made of CAL0 on boot.
-By default, CAL0 is not readable, and other NAND partitions are not writable. This is togglable via a flag.
-Boot0 now protects BCT public keys from writes by NS, and generally protects writes to the keyblob region. This should prevent losing AutoRCM on update.
=> Implement basic BIS Protection routines.

stratosphere/Makefile
It's a bit confusing that this variable is called `KIPS`, when really only some of them are KIPs.
=> stratosphere/Makefile: change KIPS to MODULES

fusee/fusee-secondary/src/stratosphere.c
Fixes compilation errors relating to the function `stat` and the struct stat.
/mnt/c/develop/Atmosphere/fusee/fusee-secondary/src/stratosphere.c:207:17: error: implicit declaration of function 'stat'; did you mean 'strcat'? [-Werror=implicit-function-declaration]
mnt/c/develop/Atmosphere/fusee/fusee-secondary/src/stratosphere.c:206:25: error: storage size of 'kip_stat' isn't known
struct stat kip_stat;
=> devkitARM r50-2 buildfix.

fusee/fusee-secondary/src/lib/fatfs/ff.h
After upgrading devkitARM to r50-3 i get this
In file included from /Users/julien/code/Atmosphere/fusee/fusee-secondary/src/fs_dev.c:28:
/Users/julien/code/Atmosphere/fusee/fusee-secondary/src/lib/fatfs/ff.h:204:3: error: conflicting types for 'DIR'
} DIR;
^~~
In file included from /opt/devkitpro/devkitARM/arm-none-eabi/include/sys/iosupport.h:13,
from /Users/julien/code/Atmosphere/fusee/fusee-secondary/src/fs_dev.c:24:
/opt/devkitpro/devkitARM/arm-none-eabi/include/sys/dirent.h:43:4: note: previous declaration of 'DIR' was here
} DIR;
^~~
fixed with editing ff.h on DIR type declaration and test if _dirent_h_ was already included so DIR is defined
=> devkitARM r50-3 buildfix

Makefile
I noticed that calling `make` (or `make clean`) with the root Makefile does not properly build (or clean) troposphere. This should fix that and prevent similar issues in the future.
=> Add component subdirectories to root Makefile's .PHONY

sept/sept-secondary/Makefile
Since most of us cannot encrypt & sign our own payload, it makes sense to allow for the usage of the pre-built one provided by 0.8.4, and skip the build process of sept-secondary.
I don't speak makefile-ese very well, so if there's a better place to put it then please feel free to suggest it, I just went for the least intrusive spot I can find.
=> Allow the user to build with a prebuilt sept-secondary blob via a SEPT_ENC_PATH variable.

sept/sept-secondary/Makefile
Hello,
This PR fixes the `make dist` after a fresh clone or clean when using the prebuild sept-secondary.enc ($SEPT_ENC_PATH)
Currently failing because sept-secondary.bin is not found
=> Fix sept-secondary build when using prebuild sept-secondary.enc

fusee/fusee-secondary/Makefile, sept/sept-secondary/Makefile
-Have fusee-secondary's makefile clean sept-secondary as required.
-Use $(TARGET) variable for sept-secondary, and clean the encrypted output as required.
Currently make clean doesn't clean sept (either stage), and when it does, it leaves the encrypted second stage binary output. I also changed the hard-coded names to be more flexible if the folder name should change in the future.
=> Makefile tweaks

docs/modules/fs_mitm.md, docs/modules/loader.md, docs/modules/set_mitm.md
Also add the list of buttons found in all cases of ParseOverrideKey. Let me know what else needs to be updated (I'm aware much of it is outdated, but I'm not familiar enough with the inner workings of AMS to rewrite them all.)
=> Add info to set_mitm docs, clean up loader docs

stratosphere/fatal/source/fatal_font.cpp
Fairly self-explanatory. Ensures va_start() is balanced with va_end()
=> fatal_font: Add missing va_end() calls to PrintFormatLine() and PrintFormat()

stratosphere/ams_mitm/source/fs_mitm/fs_dir_utils.hpp
This likely intended to get the size of the string and then subtract the null terminator byte. Instead, this would always result in a sizeof of 8.
=> fs_mitm/fs_dir_utils: Amend logic error within IterateDirectoryRecursivelyInternal

stratosphere/loader/source/ldr_content_management.cpp, stratosphere/loader/source/ldr_debug_monitor.cpp, stratosphere/loader/source/ldr_launch_queue.cpp, stratosphere/loader/source/ldr_map.cpp, stratosphere/loader/source/ldr_npdm.cpp, stratosphere/loader/source/ldr_nro.cpp, stratosphere/loader/source/ldr_nso.cpp, stratosphere/loader/source/ldr_process_creation.cpp, stratosphere/loader/source/ldr_process_manager.cpp, stratosphere/loader/source/ldr_registration.cpp, stratosphere/loader/source/ldr_ro_service.cpp
Specifying 0 as the initial entry of a structure braced initializer is a C-ism. C++ permits using an empty set of braces to signify the same behavior. Since no aggregate members are specified, this also silences -Wmissing-field-initializers warnings.
=> loader: Silence Wmissing-field-initializers warnings

stratosphere/loader/source/ldr_map.hpp
One initializer warning case that I seem to have missed in the loader code (my bad).
=> ldr_map: Silence lingering initializer warning

common/defaults/system_settings.ini, stratosphere/fatal/source/fatal_config.cpp, stratosphere/fatal/source/fatal_config.hpp, stratosphere/fatal/source/fatal_task_power.cpp
* Config (placed in system_settings under fatal_auto_reboot_interval) takes a u64 which are milliseconds
=> Implement Auto Reboot Timer (#518) 

stratosphere/creport/source/creport_debug_types.hpp, stratosphere/creport/source/creport_thread_info.cpp
Also fix FP, SP and LR registers being set wrongly by svcGetDebugThreadParam for 32 bits processes.
=> creport: Add 32 bits stack frames parsing support

stratosphere/ams_mitm/source/set_mitm/setsys_settings_items.cpp
Just tidies up the string management and makes for roughly 3 less discarded copies strings when constructing the combined name and key by using the initial std::string constructed and appending onto it. It also simplifies the text file reading in LoadConfiguration, as c_str() will always terminate it's contained string, so we can simplify the logic used to read from the file a tiny bit.
=> setsys_settings_items: Minor cleanup to string buffer management

stratosphere/ams_mitm/source/bpc_mitm/bpcmitm_main.hpp
Prevents any potential double inclusion issues from occurring. While we're at it, we can also tidy up the header's included files as well, given only the type definitions from <switch.h> are used by it. The corresponding cpp file already includes these headers.
=> bpcmitm_main: Add missing header guard

docs/building.md
Just ran into this issue following the docs, apparently installing both together is a bad idea https://pycryptodome.readthedocs.io/en/latest/src/installation.html#installation
> One must avoid having both PyCrypto and PyCryptodome installed at the same time, as they will interfere with each other.
=> Fix documentation for sept's python dependencies

fusee/fusee-primary/src/lib/vsprintf.c
Passing negative values to the macros in ctype.h other than EOF is undefined behaviour, see caveats section at https://netbsd.gw.com/cgi-bin/man-cgi?ctype++NetBSD-current
=> fix usage of ctype macros

stratosphere/ams_mitm/source/fs_mitm/fsmitm_service.cpp
libnx commit [4f441a4](https://github.com/switchbrew/libnx/commit/4f441a4f2855edddbc5193e1aab99fc855ed2480) changed SaveDataType to saveDataType.
=> Fix compilation with latest libnx master 

stratosphere/dmnt/source/cheat/impl/dmnt_cheat_vm.cpp
Previously they were performing the same behavior as the Save and ClearSave opcode types.
=> dmnt_cheat_vm: Correct register Restore and ClearRegs behavior

stratosphere/loader/source/ldr_ecs.cpp
The call to serviceCreate(...) tries to query pointer buffer size, but
since we haven't had a chance to return the server side of the session
yet, this deadlocks. Instead, we defer creating the session and
mounting the filesystem until the first time the ECS object is used.
=> loader: fix ECS after new-ipc rewrite

libraries/libstratosphere/source/ncm/ncm_package_system_update_task.cpp
Although lets be real, all the cool kids use fat32 anyway.
=> ncm: fix exfat system updates

fusee/fusee-primary/src/panic.c, libraries/libstratosphere/include/stratosphere/ams/ams_types.hpp, libraries/libstratosphere/source/ams/ams_environment.cpp
Saves some two minutes of looking at a fatal error report and a disassembly to figure out that something daborted because the stack overflowed on a sequence like this and that you might need to increase stack size:
```
sub sp, sp, 0x4f0
stp x29, x30, [sp]
```
=> Add stack overflow detection to fatal error code

stratosphere/fatal/source/fatal_config.hpp, stratosphere/fatal/source/fatal_task_power.cpp
I assumed from the existing code that quest_reboot_interval_second is stored in seconds, couldn't find it on switchbrew.
Tested and working.
=> fatal: Fix autoreboot logic (#959)

docs/building.md
During compilation the header was missing, adding the package to the list.
=> docs/building: missing required lib glm

libraries/libmesosphere/source/kern_k_server_port.cpp
Likely doesn't impact anything, but I assume this was unintended.
=> fix typo in KServerPort::Destroy()

docs/building.md
At build-time of exosphere, the `split_program.py` script is called.
It requires python module `lz4` -> https://github.com/Atmosphere-NX/Atmosphere/blob/master/exosphere/program/split_program.py
Adding lz4 to the building.md documentation.
=> Add lz4 dependency to the build instructions

libraries/libstratosphere/include/stratosphere/sf/hipc/sf_hipc_server_manager.hpp, libraries/libstratosphere/include/stratosphere/sf/hipc/sf_hipc_server_session_manager.hpp, libraries/libstratosphere/source/sf/hipc/sf_hipc_server_manager.cpp, stratosphere/sm/source/impl/sm_service_manager.cpp, stratosphere/sm/source/impl/sm_wait_list.cpp, stratosphere/sm/source/impl/sm_wait_list.hpp, stratosphere/sm/source/sm_main.cpp
This implements accurate-to-nn request deferral (plus atmosphere mitm extensions).
This substantially decreases the amount of redundant request processing required, and additionally allows for actually logging sm service calls via mesosphere without being drowned in deferred fsp-srv requests for the whole boot process.
=> sm: implement accurate request deferral semantics

stratosphere/ams_mitm/source/amsmitm_prodinfo_utils.cpp
Following a discussion on Discord.
Original message:
My guess is that HOS is now checking Rsa2048DeviceCertificate and/or Rsa2048DeviceKey at boot time. Just like EccB233DeviceCertificate and ExtendedEccB233DeviceKey, a valid CRC is not enough i.e. the console's device id must match those of EccB233DeviceCertificate + 0xC6 and of the decrypted ExtendedEccB233DeviceKey. A simple solution would be to remove line 225 and 226 (https://github.com/Atmosphere-NX/Atmosphere/blob/c547c7f0e7a5de4292b58882f261be11b288ac0e/stratosphere/ams_mitm/source/amsmitm_prodinfo_utils.cpp#L225).
It should not affect the blanking capabilities as EccB233DeviceCertificate was not blanked in the first place (because you cannot simply zero it). Blanking the SSL cert is the important stuff here.
Incognito's …
=> Fix PRODINFO blanking for newer versions.

config_templates/system_settings.ini, exosphere/program/source/smc/secmon_smc_info.cpp, exosphere/program/source/smc/secmon_smc_info.hpp, fusee/fusee-secondary/src/exocfg.h, fusee/fusee-secondary/src/nxboot.c, libraries/libexosphere/include/exosphere/secmon/secmon_monitor_context.hpp, libraries/libstratosphere/include/stratosphere/spl/spl_api.hpp, libraries/libstratosphere/include/stratosphere/spl/spl_types.hpp, libraries/libstratosphere/source/boot2/boot2_api.cpp, stratosphere/ams_mitm/source/set_mitm/settings_sd_kvs.cpp, stratosphere/loader/source/ldr_embedded_usb_patches.inc, stratosphere/loader/source/ldr_patcher.cpp, stratosphere/loader/source/ldr_patcher.hpp, stratosphere/loader/source/ldr_process_creation.cpp
This adds support for usb3.0 enable via system_settings.ini on 9.0.0+.
To work around the "usb is launched before the sd card is available" problem, we parse system_settings.ini in fusee, and pass the flag down to userland via exosphere.
We then embed usb sysmodule patches to make the module read the setting as true, when this flag is set.
Note that we only embed patches for 9.0.0+, since on older versions we can just affect the setting.
=> set.mitm: fake compatibility for usb!usb30_force_enabled on 9.0.0+

Makefile, libraries/libstratosphere/include/stratosphere/cfg/cfg_api.hpp, libraries/libstratosphere/source/boot2/boot2_api.cpp, libraries/libstratosphere/source/cfg/cfg_flags.cpp, libraries/libstratosphere/source/fs/fs_code.cpp, libraries/libstratosphere/source/ncm/ncm_submission_package_install_task.cpp
After this PR is merged, atmosphere will no longer use the /contents/ folder for its system modules.
This PR will include a mechanism for cleaning up pre-ams-0.19.0 contents, which can be removed further in the future.
This closes #927, and is critical to ever tackling #704.
=> ams: distribute sysmodules in single file as stratosphere.romfs

libraries/libstratosphere/include/stratosphere/dd/dd_types.hpp, libraries/libstratosphere/include/stratosphere/tipc/tipc_server_manager.hpp, libraries/libstratosphere/source/ncm/ncm_content_meta_database_impl.cpp, libraries/libvapours/include/vapours/util/util_bitutil.hpp
With gcc 11, we can use stuff like std::bit_cast and using enum, both of which are pretty nice.
However, we shouldn't commit gcc 11 assumption to master until a gcc 11 devkitA64 release occurs.
This branch should be merged when that happens, but not before.
In the meantime, all commits which use newer gcc features should go here.
=> Assume gcc 11

docs/features/cheats.md
This PR consists of updates to the Cheats documentation. Mainly around Code Type 0x5 and clarifying some usages of the Register Address encoding for that Code Type. This also adjusts the Code Type numbers to be written in hex throughout the document for consistency.
=> Updates to Cheats documentation

utilities/insert_splash_screen.py
Script to change splash screen was slow.
I change the code to use bytearray() instead of `+=` on a bytes (That is very slow on py3)
Time before modification
```bash
$ time python3 insert_splash_screen.py splash.png package3 
real	1m23,592s
user	0m58,354s
sys	0m25,081s
```
```bash
$ time python2 insert_splash_screen.py splash.png package3 
real	0m0,600s
user	0m0,571s
sys	0m0,014s
```
Time taken after the modification
```bash
$ time python3 insert_splash_screen.py splash.png package3 
real	0m0,606s
user	0m0,579s
sys	0m0,017s
```
```bash
$ time python2 insert_splash_screen.py splash.png package3 
real	0m0,598s
user	0m0,568s
sys	0m0,020s
```
So time reduce from `1m23s` to `0.6s` on my computer.
=> Reduce insert_splash_screen processing time from ~1m20s to ~0.6s

stratosphere/dmnt.gen2/source/dmnt2_gdb_server_impl.cpp
Currently if you enter an unknown command it can also output spurious content afterwards due to not copying the null terminator:
```
(gdb) monitor help
get info
get mappings
get mapping {address}
wait application
wait {program id}
wait homebrew
(gdb) monitor mappings
Unknown command `mappings`
apping {address}
wait application
wait {program id}
wait homebrew
```
=> Fix GDB monitor unknown command error

libraries/libmesosphere/source/board/nintendo/nx/kern_k_device_page_table.cpp, libraries/libmesosphere/source/board/nintendo/nx/kern_k_system_control.cpp, libraries/libmesosphere/source/kern_k_memory_layout.board.nintendo_nx.cpp, libraries/libmesosphere/source/kern_k_page_table_base.cpp, libraries/libmesosphere/source/kern_k_system_control_base.cpp, libraries/libmesosphere/source/kern_k_thread.cpp, libraries/libmesosphere/source/svc/kern_svc_address_translation.cpp, libraries/libmesosphere/source/svc/kern_svc_process.cpp, libraries/libstratosphere/include/stratosphere/settings/settings_types.hpp, libraries/libstratosphere/include/stratosphere/sf/cmif/sf_cmif_domain_manager.hpp, libraries/libstratosphere/include/stratosphere/sf/sf_lmem_utility.hpp, libraries/libstratosphere/include/stratosphere/sf/sf_mem_utility.hpp, libraries/libstratosphere/include/stratosphere/sf/sf_object_impl_factory.hpp, libraries/libstratosphere/include/stratosphere/sm/sm_types.hpp, libraries/libstratosphere/include/stratosphere/time/time_calendar_time.hpp, libraries/libstratosphere/include/stratosphere/tipc/impl/tipc_impl_command_serialization.hpp, libraries/libstratosphere/include/stratosphere/tipc/tipc_deferral_manager.hpp, libraries/libstratosphere/include/stratosphere/tipc/tipc_server_manager.hpp, libraries/libstratosphere/source/htclow/ctrl/htclow_ctrl_state_machine.cpp, libraries/libstratosphere/source/ncm/ncm_content_meta_database_impl.cpp, libraries/libvapours/include/vapours/results/results_common.hpp, libraries/libvapours/include/vapours/util/util_intrusive_red_black_tree.hpp, libraries/libvapours/include/vapours/util/util_optional.hpp, stratosphere/ams_mitm/source/sysupdater/sysupdater_service.cpp, stratosphere/sm/source/sm_user_service.hpp
A small set of fixes to libstratosphere headers to make stratosphere.hpp more parsable by Clang.
At the time of writing Clang has incomplete C++20 support so two of the commits add small, non-intrusive workarounds to allow Clang-based tools to still parse most of stratosphere.hpp and dump type definitions.
Unfortunately getting to 0 compilation errors is not possible at this time because Clang appears to have bugs in its constant evaluation engine and its definition of literal types does not conform to the C++17 standard. (That is the reason why the binary-search based offsetof implementation is broken in some cases on Clang.)
This PR is not just Clang workarounds though, it also fixes some non-standards-compliant code :)
=> Minor header fixes to reduce parsing issues with Clang

libraries/libstratosphere/include/stratosphere/fs/fs_memory_management.hpp, libraries/libstratosphere/include/stratosphere/fs/fs_path.hpp
This implements two optimizations on fs::Path, which N added in 12.0.0.
The current structure looks like: 
```cpp
struct Path {
const char *m_str; // Points to the read-only path string
char *m_write_buffer_buffer; // Part of std::unique_ptr<char[], ams::fs::impl::Deleter>
ams::fs::impl::Deleter m_write_buffer_deleter; // Parse of std::unique_ptr<char[], ams::fs::impl::Deleter>, stores the size of the buffer.
size_t m_write_buffer_length; // Copy of the write buffer's size accessible to the Path() structure.
bool m_is_normalized; // Whether the path buffer is normalized
};
```
This is pretty wasteful. The write buffer size is stored twice, wasting 8 bytes, because one copy of the size isn't accessible to the path.
In addition, due to alignment, the bool wastes 7 padding bytes.
This …
=> fs: reduce path size 0x28 -> 0x18

stratosphere/dmnt.gen2/source/dmnt2_gdb_server_impl.cpp
Otherwise gdb can't automatically detect the architecture.
=> gdbstub: report architecture tag for ARM targets

libraries/libmesosphere/include/mesosphere/kern_k_scheduler.hpp, mesosphere/kernel/source/arch/arm64/kern_k_scheduler_asm.s
Found these while implementing for yuzu.
=> KScheduler: fix documentation mistakes

README.md
https://reswitched.team/ is an expired domain which is now operated by someone who isn't part of the ReSwitched Team
=> Update ReSwitched Team Website

config_templates/system_settings.ini, libraries/libstratosphere/include/stratosphere/settings/settings_types.hpp, stratosphere/ams_mitm/source/set_mitm/setsys_mitm_service.cpp, stratosphere/ams_mitm/source/set_mitm/setsys_mitm_service.hpp, stratosphere/ams_mitm/source/set_mitm/setsys_shim.c, stratosphere/ams_mitm/source/set_mitm/setsys_shim.h, stratosphere/ams_mitm/source/set_mitm/settings_sd_kvs.cpp
This adds an opt-in setting to system_settings.ini to enable the console's bluetooth pairing database to be mirrored to a file on the sd card. This facilitates the synchronisation of device pairings between sysnand and/or one or more emummc setups. Paired with Mission Control's bluetooth host address spoofing feature it could even be used to unify device pairings across multiple consoles.
With the release of bluetooth audio support in firmware 13.0.0 the size of the pairing database was doubled from 10 to 20 entries, and the internal layout of fields was changed slightly. We will only store the database in the new format and convert to/from as necessary. Booting a pre-13.0.0 firmware with more than 10 paired devices present in the sd database will cause the database to be truncated to the …
=> Add system setting to mirror bluetooth pairing database to sd card

troposphere/haze/include/haze.hpp, troposphere/haze/include/haze/device_properties.hpp, troposphere/haze/source/device_properties.cpp, troposphere/haze/source/ptp_responder.cpp, troposphere/haze/source/usb_session.cpp
This unintentionally made files transferred to the device 12 bytes larger than they were supposed to be with the "set size in advance" performance optimization, which didn't account for the PTP header. This really obvious issue was unfortunately missed because the optimization was made after I had already tested roundtrips.
Also streamlines getting the device firmware version and serial number as part of a separate change.
=> haze: fix transfers to device becoming larger than intended

libraries/libmesosphere/include/mesosphere/kern_k_auto_object.hpp, libraries/libmesosphere/include/mesosphere/kern_k_typed_address.hpp, libraries/libmesosphere/include/mesosphere/kern_slab_helpers.hpp, libraries/libmesosphere/source/svc/kern_svc_physical_memory.cpp, libraries/libstratosphere/source/sf/hipc/sf_hipc_server_domain_session_manager.cpp, libraries/libvapours/include/vapours/util/util_intrusive_list.hpp, libraries/libvapours/include/vapours/util/util_intrusive_red_black_tree.hpp, stratosphere/ams_mitm/source/fs_mitm/fsmitm_romfs.cpp
GCC upgrade breaks on AMS code as usual. Going to open a separate issue to track the romfs issue this causes with Fire Emblem: Engage.
=> ams: fix compilation with gcc 13

stratosphere/dmnt.gen2/source/dmnt2_gdb_server_impl.cpp, stratosphere/dmnt.gen2/source/dmnt2_gdb_server_impl.hpp
Currently the gdb server is only used over a TCP socket. Since TCP is a reliable protocol, retransmission will not be needed. This improves performance a lot even when running over a wired network.
=> dmnt.gen2: enable gdbserver QStartNoAckMode

stratosphere/dmnt.gen2/source/dmnt2_breakpoint_manager.cpp
GetFreeBreakPoint will return nullptr when the number of breakpoints is exhausted. Prevent a null pointer dereference in this case.
=> dmnt.gen2: avoid data abort when too many breakpoints are created

stratosphere/dmnt/source/cheat/impl/dmnt_cheat_vm.cpp
This code didn't compile on master. Address issues to make it functional again.
=> dmnt: Fix debug log for cheats

fusee/program/source/sdram/fusee_sdram.cpp, libraries/config/common.mk, libraries/libstratosphere/source/ams/ams_emummc_api.cpp, libraries/libstratosphere/source/fs/fs_api.cpp, libraries/libstratosphere/source/fssrv/impl/fssrv_program_info.cpp, libraries/libstratosphere/source/htc/server/rpc/htc_rpc_task_table.hpp, libraries/libstratosphere/source/osdbg/impl/osdbg_types.hpp, libraries/libvapours/include/vapours/results/results_common.hpp, libraries/libvapours/include/vapours/svc/codegen/impl/svc_codegen_impl_code_generator.hpp, libraries/libvapours/include/vapours/svc/codegen/impl/svc_codegen_impl_layout_conversion.hpp, libraries/libvapours/include/vapours/svc/codegen/impl/svc_codegen_impl_meta_code.hpp, libraries/libvapours/include/vapours/util/arch/arm64/util_atomic.hpp, libraries/libvapours/include/vapours/util/util_typed_storage.hpp, troposphere/daybreak/Makefile, troposphere/haze/Makefile
This fixes compilation errors when upgrading to GCC 14. Unfortunately, one of the issues introduced has a natural fix (thanks to https://cplusplus.github.io/CWG/issues/2518.html) that breaks compilation with GCC 13. 
Thus, this shouldn't be merged until devkitA64 has a public release using GCC 14 available, so that we can just tell people to upgrade to latest.
=> Fix compilation with GCC 14

docs/features/cheats.md, stratosphere/dmnt/source/cheat/impl/dmnt_cheat_vm.cpp, stratosphere/dmnt/source/cheat/impl/dmnt_cheat_vm.hpp
1. Extension to Type 0
Purpose: Adding the "none" option to improve flexibility, especially when game code resides in a module. This allows the setup of register R such that R corresponds to the module's main address.
M: Memory region to write to (0 = Main NSO, 1 = Heap, 2 = Alias, 3 = Aslr, 4 = none).
2. Extension to type 5
Purpose: Introducing two new extensions for enhanced pointer chain manipulation.
Extension 2
Allows separate source and target registers, removing the need to save the source register for use in other cheats that share the initial part of a pointer chain.
`5T0R2SAA AAAAAAAA`
+ T: Width of memory read (1, 2, 4, or 8 bytes).
+ R: Register to load value into. 
+ S: Register to use as the base memory address.
+ A: Immediate offset to use from register R.
Extension 3 …
=> dmnt_extension

atmosphere.mk, exosphere/exosphere.mk, exosphere/program/program.mk, fusee/fusee.mk, fusee/program/program.mk, libraries/config/common.mk, libraries/libexosphere/libexosphere.mk, libraries/libmesosphere/libmesosphere.mk, libraries/libstratosphere/libstratosphere.mk, mesosphere/mesosphere.mk, tests/TestFs/unit_test.mk, tests/TestOsEvents/unit_test.mk, tests/TestSocket/unit_test.mk, tests/TestStack/unit_test.mk
- Invoke Python scripts with `python3` if `python` is not available.
Despite SciresM preferring Python 2, the scripts used in the build all
worked in Python 3 already, so this is just a Makefile change.
- Export `MAKE` to work around a GNU bug.
See the comment for details.
- `rmdir --ignore-fail-on-non-empty` -> `rmdir 2>/dev/null`
macOS `rmdir` doesn't support `--ignore-fail-on-non-empty`.
This is a slight downgrade in functionality, because now we ignore all
errors from `rmdir` rather than just 'Directory not empty'.  I could
have avoided this with a more complicated fix, but the benefit strikes
me as not worth the complexity.  Let me know if you disagree.
- Append `$(DEVKITPRO)/tools/bin/` to `$PATH` when invoking
`build_romfs`.
This avoids the need to add devkitPro directories to …
=> build: portability fixes
